version: '3.9'

services:
  db:
    image: postgres:16
    container_name: dsalta_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dsalta
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: dsalta_api
    depends_on:
      - db
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/dsalta?schema=public
      NODE_ENV: production
    ports:
      - '3000:3000'
    command: sh -c "npx prisma db push && node dist/server.js"

volumes:
  db_data:
